### ISSUE TITLE
Support for isomorphic store

### ISSUE THREAD

**Issue by JohnPhoto** [rangle/redux-beacon#79]
Would it be possible to let this library to just do nothing if setting up the middleware on server side render?

console:
```
ReferenceError: window is not defined
    at myProject/node_modules/redux-beacon/targets/google-tag-manager/google-tag-manager.js:11:5
    at Array.forEach (native)
    at GoogleTagManager (myProject/node_modules/redux-beacon/targets/google-tag-manager/google-tag-manager.js:4:10)
    at registerEvents (myProject/node_modules/redux-beacon/lib/register-events.js:31:5)
    at Object.dispatch (myProject/node_modules/redux-beacon/lib/create-middleware.js:20:9)
```

**Comment by ttmarek** [comment]
@JohnPhoto absolutely.

SSR is definitely something we want to support. The next release will include SSR support for at least our most popular targets (e.g. GTM, and GA).

In the interim you can create a higher-order-target. Basically just wrap the GoogleTagManager target with another function that checks to see if the window is defined.

```js
import { GoogleTagManager } from 'redux-beacon/targets/google-tag-manager';

function GTMSSR(events) {
  if(typeof window !== 'undefined') {
    GoogleTagManager(events);
  }
}

const middleware = createMiddleware(eventsMap, GTMSSR);
```

Let me know if that works. I would also gladly accept a pull request if you're inclined to make one.

**Comment by JohnPhoto** [comment]
This is what I ended up doing:

```js
import { createMiddleware } from 'redux-beacon';
import { GoogleTagManager } from 'redux-beacon/targets/google-tag-manager';
import eventsMap from './eventsMap';

const reduxMiddleWareNoop = () => next => action => next(action);

export default function createGtmMiddleware(isServer) {
  if (!isServer) { // If we don't receive req it means that we are on the client.
    return createMiddleware(eventsMap, GoogleTagManager);
  }
  return reduxMiddleWareNoop;
}

```

**Comment by JohnPhoto** [comment]
Opened a PR (#80) , I hope this is what you meant that you wanted me to help with.
